#! /usr/bin/python3

#%%
print("train start import ")
import sys
sys.path.append("/home")

import yaml, os, json
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import pickle
from BaseTrainer import Trainer

trainer = Trainer()
trainer.train()


# sagemaker_prefix = "/opt/ml"
# # debug
# # sagemaker_prefix = "/Users/kunia/Desktop/Git/AWS_Step_Function/Parallel/initial_setting"


# filename = 'model.pkl'
# sage_model_pth = os.path.join(sagemaker_prefix, filename)
# path = os.path.join(sagemaker_prefix, "iris_dataset.csv")
# print(sagemaker_prefix)
# print(path)
# ########################
# print("read_csv ...")
# df = pd.read_csv(path)
# cols = df.columns
# len_col = len(cols)
# x_cls, y_col = cols[0:(len_col-1)], cols[-1]
# X =df.loc[:, x_cls].values
# y = df.loc[:, y_col].values


# # 学習と保存
# print("start regression ...")
# reg = LinearRegression().fit(X, y)
# print("save ...")
# pickle.dump(reg, open(sage_model_pth, 'wb'))
# print("train done")

# # %%
